### ISSUE TITLE
Taking ages to start

### ISSUE THREAD

**Issue by ghost** [larkery/ido-describe-prefix-bindings.el#1]
In fact, I never waited enough time to get it working.  It may be stuck in some loop, since the mouse become a spinning animation and emacs is stuck.

Edebug informed me that it was stuck at [line 73](https://github.com/larkery/ido-describe-prefix-bindings.el/blob/a4fb97771071227299e6b09ad4acb004f34c267d/ido-describe-prefix-bindings.el#L73) `(while (search-forward-regexp re` >here< `nil t 1) ...` after the 3rd iteration of the loop.

I can provide more informations if you want.

Thank you for this package and this idea!

**Comment by larkery** [comment]
I will have a look at this soon - it is confusing because I thought that loop should always terminate, no matter what because whatever regex you use and whatever input you should eventually get to the end or a point with no match.

It would help me out if you can (a) look at search-forward-regexp and see whether it has any advice (`C-h` `f` `search-forward-regexp` `RET`), and also (b) have a look in the buffer called `*ido-describe-prefix-bindings*` (note the space on the front of the name which makes it invisible). If you could write that out to a file and attach it that would be helpful; it may be that you have some key-binding I had not accounted for.

One other thing that you could do is to edit the definition of `ido-describe-prefix-bindings` to add the statement `(insert re "\n")` on line 72 after `(search-forward "Bindings Starting")`, or `(message re)` or similar, in case the regex being generated is wrong in some way.

Thanks for the bug report :)

**Comment by larkery** [comment]
Incidentally, to switch to `" *ido-describe-prefix-bindings*"` if you have ido on you may need to use plain old switch buffer by `C-x` `b` `C-b` `SPC` `*ido-describe-prefix-bindings*` `RET`.

It seems that github markdown code styling thing removes leading spaces, so the space at the front of the name has not shown up above.

**Comment by ghost** [comment]
On `emacs-24.5 -q`:

I had a look at `search-forward-regexp` and only had the doc string:

```
search-forward-regexp is an interactive built-in function in
‘subr.el’.

(search-forward-regexp REGEXP &optional BOUND NOERROR COUNT)

Search forward from point for regular expression REGEXP.
[...]
```

Then, the content of the buffer thanks to your very accurate indications :)

[ido-describe-prefix-bindings.txt](https://github.com/larkery/ido-describe-prefix-bindings.el/files/82139/ido-describe-prefix-bindings.txt)

And then, the regex that `(message re)` produced:

```
\(?:^\(C-x r\(?:[[:space:]]?\([^[:space:]]+\)\)+\)  [[:space:]]*\([^[:space:]]+\)$\)
```

Thank you for your indications and for digging onto this issue.  I like this package!

**Comment by larkery** [comment]
This is interesting - I have compared and found
1. I can reproduce the bug - my regex appears to be hugely expensive to compute on the file you have given me, but also
2. I cannot reproduce the bug - if I do `C-x r C-h` it works.

The difference is that in my describe bindings buffer there are more spaces between the key column and the binding column than in yours. I have the same text in it otherwise.

I will see whether I can fix the regex to work, but I am also surprised that the format of that buffer has changed somehow.

What version and platform is your emacs (`M-x emacs-version`)? I have `GNU Emacs 24.4.1 (x86_64-pc-linux-gnu, GTK+ Version 3.14.5)
 of 2015-03-07 on trouble, modified by Debian`

**Comment by larkery** [comment]
I think the easiest thing I can do here is to find lines which go key prefix - some stuff - some space - a symbol name, and presume that symbol name contains no spaces. I will try that as it is typically true that commands do not contain spaces in their names.

**Comment by larkery** [comment]
I have pushed a couple of commits which might make this work better. Let me know!

**Comment by ghost** [comment]
Oh, yes, it seems flexible yet accurate.  I have little experience with repex yet.

I tested with `emacs-24.5 -q` and `emacs-25.1.0 -q`, visited the file, `M-x eval-buffer RET` `-x ido-describe-prefix-bindings-mode RET` and both have the same issue for the <kbd>C-x</kbd><kbd>r</kbd><kbd>C-h</kbd>. The diff of the `*ido-describe-prefix-bindings*` buffer do not reveal anything but the output of the command I added (`(insert re "\n")`) and an aditionnal command added in 25 I guess.

Versions:

```
GNU Emacs 25.1.50.2 (x86_64-unknown-linux-gnu, GTK+ Version 3.16.7) of 2015-12-27
```

```
GNU Emacs 24.5.1 (x86_64-unknown-linux-gnu, GTK+ Version 3.16.6) of 2015-09-10 on foutrelis
```

**Comment by ghost** [comment]
I tested the new version, and there is no more endless loop.

But now, the ivy prompt that poped do not propose any candidate.

I checked the regex with <kbd>C-M-s</kbd>, and it do not match anything on the `*ido-describe-prefix-bindings*` buffer.

Here is the content:

[ido-describe-prefix-bindings-1.txt](https://github.com/larkery/ido-describe-prefix-bindings.el/files/83011/ido-describe-prefix-bindings-1.txt)

**Comment by larkery** [comment]
This is interesting - the main issue is with this line:

```
C-x r C-SPC point-to-register
```

In my emacs there are four spaces, and in yours there is a single tab separating the columns. This must be something to do with a tab to space conversion mode I have enabled or something. I will change the regex to match the tab, and then see if I can work out how to make my emacs work like yours.

**Comment by larkery** [comment]
I have hopefully fixed this in a way that will work in general!

**Comment by ghost** [comment]
Awesome!  Thank you for the efforts and details.  I'm testing it soon.

**Comment by ghost** [comment]
I checked, and I'm sorry to announce that it still does not work (yet).

A simple reason is that the `s-pad-right` function is part of [s.el](https://github.com/magnars/s.el), and a `(require 's)` fixed the following issue:

```
concat: Symbol’s function definition is void: s-pad-right
```

It may also be [preferable to add](https://www.gnu.org/software/emacs/manual/html_node/elisp/Simple-Packages.html) the `;; Package-Requires: ((s "??"))`, you may know that better than me.

Now I got another issue and I continue debugging.

**Comment by ghost** [comment]
This is the new issue:

I run `emacs-24.5 -q` command

I eval `s.el` buffer, I eval `ido-describe-prefix-bindings.el` buffer.

I `M-x ido-describe-prefix-bindings-mode`.

I hit <kbd>M-s</kbd> <kbd>C-h</kbd>, and then, a message error briefly appear in the minibuffer:

```
Error in post-command-hook (ido-exhibit): (wrong-type-argument sequencep isearch-forward-symbol-at-point)
```

And then, I have a prompt: `Prefix commands:`, but without ido enabled, the default emacs prompt.

Hitting a key enters it on the prompt, and replaces the existent one if any.

Hitting <kbd>⌫</kbd> briefly raise this message `delete-backward-char: Text is read-only` and delete the char all the same.

Hitting <kbd>tab</kbd> briefly raise the message `ido-file-lessp: Wrong type argument: listp, isearch-forward-symbol` and nothing.

Hitting a key like <kbd>o</kbd> then <kbd>RET</kbd> runs the command `isearch-forward-symbol-at-point`, which is the first command on the list of commands starting by `M-s`.

I will try again with `ido-ubiquitous` and `ido-grid-mode`.  Good luck!

**Comment by ghost** [comment]
It works with `ido-grid-mode`!  It may be the origin of the issue.

PS: Hit the wrong button and accidentally closed the issue.

**Comment by larkery** [comment]
Ah, I use `ido-grid-mode` and haven't tested it without because I am lazy. It directly invokes `ido-completing-read` rather than plain `completing-read`, so `ido-ubiquitous` should not be needed.

I'll see if I can reproduce the issue - it may be that plain ido doesn't like the very big strings that are produced for the items to choose, and you will need `ivy`, `ido-grid-mode` or `ido-vertical-mode` for it to work right.

**Comment by larkery** [comment]
It seems that if i use `completing-read` it behaves properly. I have also amended it to have a custom option about whether to pad the 'columns', because if you are using normal ido you wouldn't want that as it looks stupid.

Hopefully this should now actually work!

**Comment by larkery** [comment]
I have also just done a quick change to add the command `ido-describe-mode-bindings` which is good on `M-X` (as opposed to `M-x`) as a listing of all the keys bound in the current mode.

**Comment by ghost** [comment]
"Lazy" but still debugging hard!

This time it is working very well (with ivy, that is).

I couldn't expect these two things:
1. I do not get the latest sources yet by pulling (only a small delay ?)
2. Removing the `ido-` from the `ido-completing-read`, and only this fixed the issue and made it completion-system agnostic (as I've seen on your commit).

So I will test it further more while pulling the latest commits.

Thank you: you didn't gave up and now it works fine!

**Comment by ghost** [comment]
This is now working pretty well, and the command to describe mode binding is also very good!

I close the issue and open a discussion on Reddit ! (if you don't mind)

**Comment by larkery** [comment]
I am glad that is fixed for you. You are welcome to discuss it on reddit, or wherever you like really!

**Comment by ghost** [comment]
[Here](https://www.reddit.com/r/emacs/comments/40p7e3/list_keybindings_with_your_favorite_completion/) we go.

It seems that this have been usefull to make [`counsel-descbind`](https://github.com/abo-abo/swiper/commit/d996215c9e2757deae391619839037cbbdfa7b9c).
